export const GET_ALL_ANSWERS_SUCCESS = "GET_ALL_ANSWERS_SUCCESS";
export const GET_ALL_ANSWERS_FAIL = "GET_ALL_ANSWERS_FAIL";
export const GET_ALL_QUESTIONS_FAIL = "GET_ALL_ANSWERS_FAIL";
export const CAL_SCORE_OF_TEST_SUCCESS = "CAL_SCORE_OF_TEST_SUCCESS";
export const CAL_SCORE_OF_TEST_FAIL = "CAL_SCORE_OF_TEST_FAIL";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_ANSWERS_SUCCESS";
export const CAL_SCORE_OF_TEST5_SUCCESS = "CAL_SCORE_OF_TEST5_SUCCESS";
export const CAL_SCORE_OF_TEST5_FAIL = "CAL_SCORE_OF_TEST5_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const FIRST_STEP_REGISTER_FAIL = "FIRST_STEP_REGISTER_FAIL";
export const FIRST_STEP_REGISTER_SUCCESS = "FIRST_STEP_REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const FIRST_STEP = "FIRST_STEP";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOADING = "SET_LOADING";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const UPDATE_ITEM_IN_USER_SUCCESS = "UPDATE_ITEM_IN_USER_SUCCESS";
export const UPDATE_ITEM_IN_USER_FAIL = "UPDATE_ITEM_IN_USER_FAIL";
export const UPLOAD_USER_PIC_FILE_SUCCESS = "UPLOAD_USER_PIC_FILE_SUCCESS";
export const UPLOAD_USER_PIC_FILE_FAIL = "UPLOAD_USER_PIC_FILE_FAIL";
export const DOWNLOAD_USER_PIC_BY_USER_ID_FAIL =
  "DOWNLOAD_USER_PIC_BY_USER_ID_FAIL";
export const DOWNLOAD_USER_PIC_BY_USER_ID_SUCCESS =
  "DOWNLOAD_USER_PIC_BY_USER_ID_SUCCESS";
export const GET_TEST_FOR_SPECIFIC_USER_SUCCESS =
  "GET_TEST_FOR_SPECIFIC_USER_SUCCESS";
export const GET_TEST_FOR_SPECIFIC_USER_FAIL =
  "GET_TEST_FOR_SPECIFIC_USER_FAIL";
export const CAL_SCORE_OF_TEST117_SUCCESS = "CAL_SCORE_OF_TEST117_SUCCESS";
export const CAL_SCORE_OF_TEST117_FAIL = "CAL_SCORE_OF_TEST117_FAIL";
export const DOWNLOAD_TEST_FILE_BY_ID_FAIL = "DOWNLOAD_TEST_FILE_BY_ID_FAIL";
export const DOWNLOAD_TEST_FILE_BY_ID_SUCCESS =
  "DOWNLOAD_TEST_FILE_BY_ID_SUCCESS";
export const SET_USER_ID_FOR_SHOWING_RESULT = "SET_USER_ID_FOR_SHOWING_RESULT";
export const CAL_SCORE_OF_TEST5_JUST_FOR_SHOW_RESULT_SUCCESS =
  "CAL_SCORE_OF_TEST5_JUST_FOR_SHOW_RESULT_SUCCESS";
export const CAL_SCORE_OF_TEST5_JUST_FOR_SHOW_RESULT_FAIL =
  "CAL_SCORE_OF_TEST5_JUST_FOR_SHOW_RESULT_FAIL";
export const SET_CAL_SCORE_FOR_TEST_5 = "SET_CAL_SCORE_FOR_TEST_5";
export const GET_ALL_USER_FOR_SPECIFIC_GROUP_SUCCESS =
  "GET_ALL_USER_FOR_SPECIFIC_GROUP_SUCCESS";
export const GET_ALL_USER_FOR_SPECIFIC_GROUP_FAIL =
  "GET_ALL_USER_FOR_SPECIFIC_GROUP_FAIL";
export const GET_USER_INFO_BY_ID_SUCCESS = "GET_USER_INFO_BY_ID_SUCCESS";
export const GET_USER_INFO_BY_ID_FAIL = "GET_USER_INFO_BY_ID_FAIL";
export const SET_TEST_ID_FOR_SHOWING_RESULT = "SET_TEST_ID_FOR_SHOWING_RESULT";
export const CAL_SCORE_OF_TEST117_JUST_FOR_SHOW_RESULT_SUCCESS =
  "CAL_SCORE_OF_TEST117_JUST_FOR_SHOW_RESULT_SUCCESS";
export const CAL_SCORE_OF_TEST117_JUST_FOR_SHOW_RESULT_FAIL =
  "CAL_SCORE_OF_TEST117_JUST_FOR_SHOW_RESULT_FAIL";
export const CAL_SCORE_OF_TEST_JUST_FOR_SHOW_RESULT_SUCCESS =
  "CAL_SCORE_OF_TEST_JUST_FOR_SHOW_RESULT_SUCCESS";
export const CAL_SCORE_OF_TEST_JUST_FOR_SHOW_RESULT_FAIL =
  "CAL_SCORE_OF_TEST_JUST_FOR_SHOW_RESULT_FAIL";
