export const GET_ALL_ANSWERS_SUCCESS = "GET_ALL_ANSWERS_SUCCESS";
export const GET_ALL_ANSWERS_FAIL = "GET_ALL_ANSWERS_FAIL";
export const GET_ALL_QUESTIONS_FAIL = "GET_ALL_ANSWERS_FAIL";
export const CAL_SCORE_OF_TEST_SUCCESS = "CAL_SCORE_OF_TEST_SUCCESS";
export const CAL_SCORE_OF_TEST_FAIL = "CAL_SCORE_OF_TEST_FAIL";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_ANSWERS_SUCCESS";
